[firebase]
apiKey = "AIzaSyCP1orTUVVA4u8JMYsi_Cn5M0V1wwZ8e3g"
authDomain = "financial-analysis-platform.firebaseapp.com"
projectId = "financial-analysis-platform"
storageBucket = "financial-analysis-platform.firebasestorage.app"
messagingSenderId = "307624566797"
appId = "1:307624566797:web:3d1dd6fc739ba87c7ff544"

[firebase_admin]
service_account_json = "{...}"
